; Loaded after php.ini-production.

memory_limit = 256M
max_execution_time = 90
expose_php = Off
date.timezone = UTC

display_errors = Off
log_errors = On

; Code only changes with a new image.
opcache.enable = 1
opcache.validate_timestamps = 0
